# Generated by Django 2.1.7 on 2019-03-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0003_auto_20190322_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfile',
            name='isvisible',
            field=models.CharField(default='off', max_length=3),
        ),
    ]
