# Generated by Django 2.1.7 on 2019-03-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0004_auto_20190322_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicfile',
            name='isdownloaded',
            field=models.CharField(default='on', max_length=3),
        ),
    ]
