# Generated by Django 2.1.7 on 2019-03-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0005_publicfile_isdownloaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfile',
            name='path',
            field=models.FilePathField(max_length=100000),
        ),
    ]
