# Generated by Django 2.1.7 on 2019-03-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0006_auto_20190324_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicfile',
            name='isvisible',
            field=models.CharField(default='false', max_length=5),
        ),
    ]
